samples: [
  "SRR30401469",
  "SRR30401467",
  "SRR30401459",
  "SRR30401457"
  ]

samplesheet: "/home/lauris/RNAseq_2026_SysBio/samplesheet.csv"

input_path: "/home/lauris/RNAseq_2026_SysBio/raw_data"

genome_index: "/home/lauris/RNAseq_2026_SysBio/Homo_sapiens.GRCh38/genome_tran"

gtf_file: "/home/lauris/RNAseq_2026_SysBio/Homo_sapiens.GRCh38/genome.gtf"